# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Path of the model to package'
        default: 'keras'
        type: string
      version:
        description: 'Version the package to build'
        default: '1'
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
    - name: Create randomized text file
      run: |
         python src/test.py
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: randomized-file
        path: ./result/random.txt